[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "parameter_store_to_dot_env"
version = "0.1.0"
description = "as the name, it helps yo dump key/value from aws paramter store"
authors = [{name = "tim", email = "tim.yellow@gmail.com"}]
readme = "README.md"
license = "MIT"

[project.dependencies]
click = "^8.0.0"
ssm_parameter_store = "^0.0.22"

[project.scripts]
aws-parameter-store = "aws_parameter_store:main"
